Ft fix pep8 errors 150398504
andela/wger-lycan-clan pull request #1
Opened 2017-08-25 07:24 UTC by brayoh

#### What does this PR do?
Fix Python coding style warnings/errors

#### Description of Task to be completed?
many errors ensue from running flake8. these require fixing.

#### How should this be manually tested?
cd to the project directory and run `pep8 .`
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
150398504
#### Screenshots (if appropriate)
N/A
#### Questions:
N/A

2017-08-25 12:06 UTC, egichuri requested changes

2017-08-25 12:06 UTC, egichuri commented on .travis.yml
> -
changes to travis are being handled in a different branch

2017-08-25 12:07 UTC, egichuri commented
let's change the base branch for this pr to `develop`

2017-08-28 10:40 UTC, egichuri commented
@brayoh please change the base branch for this

2017-08-28 11:14 UTC, brayoh commented
@egichuri I've changed the branch to develop

2017-08-28 11:44 UTC, egichuri approved these changes

2017-08-28 11:46 UTC, merged